[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20030eaff1f8f47d3646fc99d415a823516778d7"
libc = "glibc"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "f3cd1c89a9dbd251d962d996b45af80dc78ea84ec1228f8a052c514082bd3e36"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v4.5.2+1/hsa_rocr.v4.5.2.x86_64-linux-gnu-cxx11.tar.gz"
[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1feeec10c90b835f0b7e1a2142c3a42ed19c8a9"
libc = "musl"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "4bf4fe8532c95b3e318328375c77d6eab7e5a29a1f717e552a2dfc0f1734c893"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v4.5.2+1/hsa_rocr.v4.5.2.x86_64-linux-musl-cxx11.tar.gz"
