[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60b7f74a73d603a978ab2a9ccd589133bddda392"
libc = "glibc"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "d38424525b2499a94aba57dfef53902e61f8ef7bac820dd834371a0a7cf3eb08"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v4.2.0+1/hsa_rocr.v4.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1aa837f69ba67b20f9654af56c818e6d9bfd262"
libc = "glibc"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "d6facab1e41ad18cbf42b697afb6e15c9ba2bf207122af0e6d4a75961cd04a4d"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v4.2.0+1/hsa_rocr.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0d34d98936adf6070a3f823495d08fee23b1623"
libc = "musl"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "5599005716db6ca6af0f89421f65267d45a389bf9681377b17958dfc5e19fcea"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v4.2.0+1/hsa_rocr.v4.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5399b6e34631461e881ba36c09ed17dfe02d062e"
libc = "musl"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "7d230c53c6e35d6a0e7c731e4be3f2266744585c53d02d1c860d5926a1d7c49d"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v4.2.0+1/hsa_rocr.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"
