[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "169e9a933365dbab116a56e28d5e468c5c7a10c5"
libc = "glibc"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "9fa6396fffc1060cec9ad2eebfa3f4023586b04318c97f0b4a949185e5acc3ea"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v4.2.0+2/hsa_rocr.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ce9e463158b875144d3efeecf75ecb4bae9bddf"
libc = "musl"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "0eca182ee7cba1820780cde61f29ca7b77add74c41b11511d12bfdb48742c401"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v4.2.0+2/hsa_rocr.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"
