[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f65dd5b8ccd425fc88772406b0deacbfab0a9382"
libc = "glibc"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "ef04ef4f33077f6d84e70b7616cfaca9aca4e56ccb496b9a30e0b4d5713574f8"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v4.2.0+0/hsa_rocr.v4.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a5953309081bc042d3781a6ceed81a5ff287d9a"
libc = "glibc"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "6eb5b4272ae5778269dbb42b133952e818390bf2759b697197a41c4f34565901"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v4.2.0+0/hsa_rocr.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a31eab64bebe7250738ea8da77cccfc8bb876c1a"
libc = "musl"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "796f8ffe0f607ee057098d92a77eff700695254ce2549e88c06b6ed878ff039c"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v4.2.0+0/hsa_rocr.v4.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0259ffc2febc7909a054615bef7146a29c69fca"
libc = "musl"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "4e52f054b65e7f9b0e9bb652d718bb901ddb640a1c15621d66dadb00cc7a34cf"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v4.2.0+0/hsa_rocr.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"
