[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4df816456579cea2c03cac08a6b82fa87abe2b38"
libc = "glibc"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "6d26a5a496b0c5472ea10f2bf47373515fbdf770a33532642140e754b42c2364"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v5.4.4+0/hsa_rocr.v5.4.4.x86_64-linux-gnu-cxx11.tar.gz"
[[hsa_rocr]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21108ac2979cdf8769596bcc8d27dbd41ee46ff4"
libc = "musl"
os = "linux"

    [[hsa_rocr.download]]
    sha256 = "a73856e046324771c30f35a7abf8791d035970c7b1b10a4d6a514968bdf68015"
    url = "https://github.com/JuliaBinaryWrappers/hsa_rocr_jll.jl/releases/download/hsa_rocr-v5.4.4+0/hsa_rocr.v5.4.4.x86_64-linux-musl-cxx11.tar.gz"
