# Autogenerated wrapper script for hsa_rocr_jll for x86_64-linux-musl-cxx03
export libhsa_runtime64

using hsakmt_roct_jll
using NUMA_jll
using Zlib_jll
using Elfutils_jll
JLLWrappers.@generate_wrapper_header("hsa_rocr")
JLLWrappers.@declare_library_product(libhsa_runtime64, "libhsa-runtime64.so.1")
function __init__()
    JLLWrappers.@generate_init_header(hsakmt_roct_jll, NUMA_jll, Zlib_jll, Elfutils_jll)
    JLLWrappers.@init_library_product(
        libhsa_runtime64,
        "lib/libhsa-runtime64.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
